# This file was generated by GoReleaser. DO NOT EDIT.
cask "marginalia" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "2eae242e4180995be25afec73ec8809580c32d1bcbf7bed19a3fcf5e4d03a899"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62cc54b5d4a9e60035dca9c98d441d0ca053c26ea7df738d0a5a93781a7d510f"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "735a9a1912eafc9a1c751b71a636e2840887a17f9d8d1cf5d3764d9024fbaedf"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d25804b5acd5f9d03a31fe2bd834d09b8263c64e2bfd30055d70197b866a514"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_linux_amd64.tar.gz"
    end
  end

  name "marginalia"
  desc "Hand an agent-authored document to a human for block-anchored review"
  homepage "https://github.com/gruesomeparty/marginalia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marginalia"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marginalia"]
    end
  end

  # No zap stanza required
end
