# This file was generated by GoReleaser. DO NOT EDIT.
cask "marginalia" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "a7ddbcc50f3582ffcbc208a4b28d1a254d03736058bc54c5ff355df14ccf04ee"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "549053d4ac2d48433ec79393630e9a029981e5dd4a355b941a0f5d7f2782a397"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c38ebf0baea0b13ed130bfb3e3972190b4d0a3db4cff872391eee9d58b7a4b76"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "416e9c01fcc3fc23d927c03dff97597320f083f357cf64999bbdf1b44b6d88e1"
      url "https://github.com/gruesomeparty/marginalia/releases/download/v#{version}/marginalia_#{version}_linux_amd64.tar.gz"
    end
  end

  name "marginalia"
  desc "Hand an agent-authored document to a human for block-anchored review"
  homepage "https://github.com/gruesomeparty/marginalia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marginalia"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marginalia"]
    end
  end

  # No zap stanza required
end
